{
    'name': "Ksolves Theme Base",

    'summary': """
        Ksolves Theme Base""",

    'description': """
        ecommerce theme,
        best ecommerce theme,
        frontend theme,
        odoo theme,
        spa theme,
        beauty theme,
        fitness theme,
        corporate theme,
        business theme,
        enterprise theme,
        community theme,
        community,
        enterprise,  
        best enterprise theme,
        best community theme,
        best odoo theme,
        best odoo themes,
        top odoo theme,
        top frontend odoo theme,
        best frontend odoo theme,
        clarico,
        alan,
        number 1 odoo theme,
        number 1 theme,
        beautiful odoo theme,
        stunning odoo theme,
        Ksolves,
        Ksolves India Private Limited,
        Ksolves India Pvt. Ltd,
        Ksolves India Private Limited odoo apps,
        Ksolves India Pvt. Ltd. odoo apps,
        Ksolves odoo apps,
        Ksolves apps,
        Ksolves odoo,
        Ksolves odoo themes,
        Ksolves themes, 
        Ksolves theme,
        Ksolves odoo app, 
        odoo apps,
    """,

    'author': "Ksolves India Pvt. Ltd.",
    'website': "https://www.ksolves.com/",
    'license': 'OPL-1',
    'currency': 'EUR',
    'price': '30.0',
    'category': 'tools',
    'version': '2.0.2',

    'depends': ['base', 'website_blog', 'sale_management', 'website_sale', 'website_theme_install', 'rating'],

    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/ks_product_category.xml',
        'views/ks_product_tags.xml',
        'views/ks_product_grid.xml',
        'views/ks_product_slider.xml',
        'views/ks_main_slider.xml',
        'views/ks_brand_view.xml',
        'data/ks_featured.xml',
    ],
    'images': [
        'static/description/banner.png',
    ],
    "application": True,

}
# -*- coding: utf-8 -*-
